version: "3"

networks:
  monitoring:
    driver: bridge


services:
  application:
    image: ${IMAGE_NAME}
    container_name: sensor-fault
    ports:
      - "8080:8080"
    environment:
      - CONTAINER_NAME=${CONTAINER_NAME}
      - CONNECTION_STRING=${CONNECTION_STRING}
      - MONGO_DB_URL=${MONGO_DB_URL}
    volumes:
      - "./airflow/dags:/app/airflow/dags"
      - "./airflow/logs:/app/airflow/logs"
