version: 2.1


jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout
      - run:
          name: lint code
          command: echo "Linting repository"
      - run:
          name: run unit tests
          command: echo "Running unit tests"
  continuous-delivery:
    docker:
      - image: cimg/base:stable 
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - azure-acr/acr-login:
          configure-docker-credentials-store: true 
          registry-name: sensorfaultdocker
      - azure-acr/build-and-push-image:
          login-server-name: sensorfaultdocker.azurecr.io
          registry-name: sensorfaultdocker
          repo: sensor-fault
          tag: latest

workflows:
  CICD:
    jobs:
      - continuous-integration

      - continuous-delivery:
          requires:
            - continuous-integration
