version: 2.1


jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout
      - run:
          name: lint code
          command: echo "Linting repository"
      - run:
          name: run unit tests
          command: echo "Running unit tests"
  continuous-delivery:
    docker:
      - image: cimg/base:stable 
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Azure Container Registry
          command: echo $AZURE_REGISTRY_PASSWORD | docker login $AZURE_REGISTRY_NAME.azurecr.io --username $AZURE_REGISTRY_USERNAME --password-stdin
      - run:
          name: Build docker
          command: docker build -t $AZURE_REGISTRY_NAME.azurecr.io/$IMAGE_NAME:$TAG .
      - run:
          name: push to azure container registry
          command: docker push $AZURE_REGISTRY_NAME.azurecr.io/$IMAGE_NAME:$TAG
  runner-test:
    machine: true
    resource_class: nikeshkaza/self-hosted
    steps:
      - run: echo "Hi I'm on Runners!"


workflows:
  CICD:
    jobs:
      - runner-test
      - continuous-integration:
          requires:
            - runner-test

      - continuous-delivery:
          requires:
            - continuous-integration
