version: 2.1


jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout
      - run:
          name: lint code
          command: echo "Linting repository"
      - run:
          name: run unit tests
          command: echo "Running unit tests"
  continuous-delivery:
    docker:
      - image: cimg/base:stable 
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Azure Container Registry
          command: echo $AZURE_REGISTRY_PASSWORD | docker login -u $AZURE_REGISTRY_USERNAME --password-stdin $AZURE_REGISTRY_NAME
      - run:
          name: Build and tag docker
          command: 
          docker build -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG $AZURE_REGISTRY_NAME.azurecr.io/$IMAGE_NAME:$TAG
      - run:
          name: push to azure container registry
          command: docker push $AZURE_REGISTRY_NAME.azurecr.io/$IMAGE_NAME:$TAG


workflows:
  CICD:
    jobs:
      - continuous-integration

      - continuous-delivery:
          requires:
            - continuous-integration
